name: Quality

on:
  push:
    branches:
      - '**'
      - '!master'
      - '!main'
  pull_request:
    branches:
      - '**'
      - '!master'
      - '!main'

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install Dependencies
        run: npm ci

      - name: Tests
        run: npm run test

      # TODO Run Lints etc.
